version: '3'

services:

  client:
    container_name: as_client
    build: ./
    volumes:
      - ./:/usr/src/app
      - client_node_modules:/usr/src/app/node_modules
    command: bash -c "cd /usr/src/app && touch npm-debug.log && tail -f npm-debug.log"
    ports:
      - "4200:4200"

volumes:
  client_node_modules:

networks:
  back-tier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
